### ISSUE TITLE
UI layout is messed up at screen width at 700px

### ISSUE THREAD

**Issue by mydu** [medialab/website#477]
How to reproduce:
Open any page, and set screen width to 700px, the topbar and main section are not aligned properly.

**Investigation**: set media queries multiple times at width:700px

**Comment by BenjmnG** [comment]
Hi Mydu, 

You're right.

I set new limits for mobile CSS rules. 
Previous values was 700px, now it's 699px.
It's cleaner because desktop CSS rules start at 700px.

Best way to finish the job is to proceed a "find & replace" and locate hypothetical vestige.
I can't do it now, cos' my local installation is out of working.

**Comment by mydu** [comment]
@BenjmnG yeah, I had tested your fix locally and it will be broken again at 699px, I will find and fix it on my side.

**Comment by BenjmnG** [comment]
Ok let me known
