### ISSUE TITLE
Search field in "Activités" produces offset text highlights

### ISSUE THREAD

**Issue by diegantobass** [medialab/website#532]
Firefox 85.0.1 on Kubuntu 20.10, on Tuesday 16th of Februar 2021

Search for "projet" in the activités submenu (with default filters) will highlight the first 2 occurrences of the world "projets" in the short descriptions but yields incorrect results further down the list of posts.

Screenshot
![issuesite](https://user-images.githubusercontent.com/9825192/108061527-bf121b80-7058-11eb-80be-e2624b01ebdd.jpeg)

**Comment by boogheta** [comment]
cute one!

**Comment by Yomguithereal** [comment]
So this one is a bit tricky because we are deburring strings when searching since we want to normalize those pesky latin accents. This means the regex match indices can be offset from the original string positions since some characters (typically two-char French "é") resolve to a single char when normalized. This is why we usually don't re-implement search because ctrl+F is a sensible option :P. I will try to find a quick & dirty solution though.

**Comment by RouxRC** [comment]
gg!
